create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron;

create table if not exists public.push_private_config (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);
alter table public.push_private_config enable row level security;

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  profile_id text not null references public.profiles(id) on delete cascade,
  auth_user_id uuid,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text not null default '',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.push_subscriptions enable row level security;
create index if not exists push_subscriptions_profile_idx on public.push_subscriptions(profile_id) where enabled;

create table if not exists public.notification_outbox (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor_profile_id text,
  target_profile_id text,
  title text not null default '여린교회',
  body text not null,
  data jsonb not null default '{}'::jsonb,
  dedupe_key text not null unique,
  not_before timestamptz not null default now(),
  created_at timestamptz not null default now(),
  sent_at timestamptz
);
alter table public.notification_outbox enable row level security;
create index if not exists notification_outbox_due_idx on public.notification_outbox(sent_at,not_before,id) where sent_at is null;

create or replace function public.yeorin_notify_new_qt() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.notification_outbox(event_type,actor_profile_id,title,body,data,dedupe_key)
  values('qt_new',new.author_id,'여린교회','새로운 나눔이 등록됐어요',jsonb_build_object('tab','nanum','sub','qt','date',new.post_date::text,'postId',new.id),'qt_new:'||new.id)
  on conflict(dedupe_key) do nothing;
  return new;
end $$;
drop trigger if exists trg_yeorin_notify_new_qt on public.qt_posts;
create trigger trg_yeorin_notify_new_qt after insert on public.qt_posts for each row execute function public.yeorin_notify_new_qt();

create or replace function public.yeorin_notify_new_prayer() returns trigger language plpgsql security definer set search_path=public as $$
declare v_body text;
begin
  v_body:=case when coalesce(new.post_type,'prayer')='thanks' then '새로운 감사 나눔이 등록됐어요' else '새로운 기도제목이 등록됐어요' end;
  insert into public.notification_outbox(event_type,actor_profile_id,title,body,data,dedupe_key)
  values('prayer_new',new.author_id,'여린교회',v_body,jsonb_build_object('tab','nanum','sub','prayer','date',new.post_date::text,'postId',new.id),'prayer_new:'||new.id)
  on conflict(dedupe_key) do nothing;
  return new;
end $$;
drop trigger if exists trg_yeorin_notify_new_prayer on public.prayer_posts;
create trigger trg_yeorin_notify_new_prayer after insert on public.prayer_posts for each row execute function public.yeorin_notify_new_prayer();

create or replace function public.yeorin_notify_new_community() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.notification_outbox(event_type,actor_profile_id,title,body,data,dedupe_key)
  values('community_new',new.author_id,'여린교회','커뮤니티에 새 글이 등록됐어요',jsonb_build_object('tab','community','postId',new.id::text),'community_new:'||new.id::text)
  on conflict(dedupe_key) do nothing;
  return new;
end $$;
drop trigger if exists trg_yeorin_notify_new_community on public.community_posts;
create trigger trg_yeorin_notify_new_community after insert on public.community_posts for each row execute function public.yeorin_notify_new_community();

create or replace function public.yeorin_notification_target(p_type text,p_id text) returns jsonb language plpgsql stable security definer set search_path=public as $$
declare v_author text; v_data jsonb;
begin
  if p_type='community' then
    select author_id, jsonb_build_object('tab','community','postId',id::text) into v_author,v_data from public.community_posts where id::text=p_id;
  elsif p_type='qt' then
    select author_id, jsonb_build_object('tab','nanum','sub','qt','date',post_date::text,'postId',id) into v_author,v_data from public.qt_posts where id=p_id;
  elsif p_type='prayer' then
    select author_id, jsonb_build_object('tab','nanum','sub','prayer','date',post_date::text,'postId',id) into v_author,v_data from public.prayer_posts where id=p_id;
  else return null; end if;
  if v_author is null then return null; end if;
  return jsonb_build_object('authorId',v_author,'data',coalesce(v_data,'{}'::jsonb));
end $$;

create or replace function public.yeorin_notify_reaction() returns trigger language plpgsql security definer set search_path=public as $$
declare v_target jsonb; v_author text; v_actor_name text; v_data jsonb;
begin
  if new.reaction_key<>'heart' then return new; end if;
  v_target:=public.yeorin_notification_target(new.target_type,new.target_id);if v_target is null then return new; end if;
  v_author:=v_target->>'authorId';if v_author is null or v_author=new.user_id then return new; end if;
  select name into v_actor_name from public.profiles where id=new.user_id;v_data:=coalesce(v_target->'data','{}'::jsonb);
  insert into public.notification_outbox(event_type,actor_profile_id,target_profile_id,title,body,data,dedupe_key)
  values('reaction',new.user_id,v_author,'여린교회',coalesce(v_actor_name,'누군가')||'님이 내 글에 좋아요를 눌렀어요',v_data,'reaction:'||new.target_type||':'||new.target_id||':'||new.user_id||':'||new.reaction_key)
  on conflict(dedupe_key) do nothing;
  return new;
end $$;
drop trigger if exists trg_yeorin_notify_reaction on public.reactions;
create trigger trg_yeorin_notify_reaction after insert on public.reactions for each row execute function public.yeorin_notify_reaction();

create or replace function public.yeorin_notify_comment() returns trigger language plpgsql security definer set search_path=public as $$
declare v_target jsonb; v_author text; v_actor_name text; v_data jsonb;
begin
  v_target:=public.yeorin_notification_target(new.target_type,new.target_id);if v_target is null then return new; end if;
  v_author:=v_target->>'authorId';if v_author is null or v_author=new.author_id then return new; end if;
  select name into v_actor_name from public.profiles where id=new.author_id;v_data:=coalesce(v_target->'data','{}'::jsonb);
  insert into public.notification_outbox(event_type,actor_profile_id,target_profile_id,title,body,data,dedupe_key)
  values('comment',new.author_id,v_author,'여린교회',coalesce(v_actor_name,'누군가')||'님이 내 글에 댓글을 남겼어요',v_data,'comment:'||new.id)
  on conflict(dedupe_key) do nothing;
  return new;
end $$;
drop trigger if exists trg_yeorin_notify_comment on public.comments;
create trigger trg_yeorin_notify_comment after insert on public.comments for each row execute function public.yeorin_notify_comment();

create or replace function public.yeorin_enqueue_calendar_notifications() returns void language plpgsql security definer set search_path=public as $$
declare v_now timestamp:=timezone('Asia/Seoul',now());v_today date:=timezone('Asia/Seoul',now())::date;v_tomorrow date:=timezone('Asia/Seoul',now())::date+1;r record;
begin
  if extract(hour from v_now)=9 then
    for r in select id,title,event_date from public.calendar_events where type='birthday' and to_char(event_date,'MM-DD')=to_char(v_today,'MM-DD') loop
      insert into public.notification_outbox(event_type,title,body,data,dedupe_key) values('birthday_today','여린교회','오늘은 '||r.title||'님 생일이에요 🎉',jsonb_build_object('tab','calendar','date',v_today::text),'birthday_today:'||v_today::text||':'||r.id) on conflict(dedupe_key) do nothing;
    end loop;
    for r in select id,title,event_date from public.calendar_events where type='birthday' and to_char(event_date,'MM-DD')=to_char(v_tomorrow,'MM-DD') loop
      insert into public.notification_outbox(event_type,title,body,data,dedupe_key) values('birthday_tomorrow','여린교회','내일은 '||r.title||'님 생일이에요 🎂',jsonb_build_object('tab','calendar','date',v_tomorrow::text),'birthday_tomorrow:'||v_today::text||':'||r.id) on conflict(dedupe_key) do nothing;
    end loop;
  end if;
  if extract(hour from v_now)=19 then
    for r in select id,title,event_date,start_time from public.calendar_events where type<>'birthday' and event_date=v_tomorrow loop
      insert into public.notification_outbox(event_type,title,body,data,dedupe_key) values('calendar_tomorrow','여린교회','내일 '||r.title||' 일정이 있어요'||case when coalesce(r.start_time,'')<>'' then ' · '||r.start_time else '' end,jsonb_build_object('tab','calendar','date',v_tomorrow::text),'calendar_tomorrow:'||v_today::text||':'||r.id) on conflict(dedupe_key) do nothing;
    end loop;
  end if;
end $$;

create or replace function public.yeorin_push_dispatch_ping() returns void language plpgsql security definer set search_path=public,extensions as $$
declare v_secret text;
begin
  select value into v_secret from public.push_private_config where key='cron_secret';if coalesce(v_secret,'')='' then return; end if;
  perform net.http_post(url:='https://putqauaiboychaalgyew.supabase.co/functions/v1/yeorin-push',headers:=jsonb_build_object('Content-Type','application/json','x-yeorin-cron',v_secret),body:='{"action":"dispatch"}'::jsonb,timeout_milliseconds:=15000);
end $$;

revoke all on public.push_private_config from anon,authenticated;
revoke all on public.push_subscriptions from anon,authenticated;
revoke all on public.notification_outbox from anon,authenticated;
revoke all on function public.yeorin_enqueue_calendar_notifications() from public,anon,authenticated;
revoke all on function public.yeorin_push_dispatch_ping() from public,anon,authenticated;
revoke all on function public.yeorin_notification_target(text,text) from public,anon,authenticated;

select cron.unschedule(jobid) from cron.job where jobname='yeorin-push-dispatch';
select cron.schedule('yeorin-push-dispatch','* * * * *','select public.yeorin_push_dispatch_ping();');
